"""界面文案集中管理（简体中文）。"""
from __future__ import annotations

STR = {
    # 窗口与托盘
    "app_title": "中转站 TransStation",
    "app_title_short": "中转站",
    "tray_tooltip": "中转站 TransStation · 呼出：{hotkey}",
    "tray_show": "显示面板",
    "tray_settings": "设置…",
    "tray_open_data": "打开数据目录",
    "tray_report": "打开报表",
    "tray_quit": "退出",
    "tray_quit_confirm": "退出中转站？托盘图标将一并移除。",
    "tray_hotkey_error": "快捷键注册失败：{msg}\n可在“设置 → 呼出与窗口”中修改快捷键。",
    "already_running": "中转站已在运行，已为你唤出面板。",
    # 面板
    "panel_source_from": "来自 {app}",
    "search_placeholder": "搜索标题、内容或备注…",
    "filter_all": "全部",
    "filter_file": "文件",
    "filter_link": "链接",
    "filter_text": "文本",
    "filter_image": "图片",
    "filter_bad": "失效链接",
    "drop_hint": "松开鼠标，存入中转站",
    "drop_hint_multi": "松开鼠标，存入 {n} 项",
    "btn_clipboard_add": "从剪贴板添加",
    "empty_title": "这里还是空的",
    "empty_desc": "在任意应用按住文件、文字或图片拖动，\n同时按 {hotkey}，在中转站上松手即可暂存。",
    "empty_desc2": "也可以先在别处复制内容，再点上方按钮加入。",
    "btn_try_clipboard": "从剪贴板添加",
    "status_counts": "共 {total} 项 · 本周使用 {weekly} 次",
    "status_report": "报表",
    "status_settings": "设置",
    "toast_stored": "已存入 {n} 项",
    "toast_stored_one": "已存入：{title}",
    "toast_undo": "撤销",
    "toast_deleted": "已删除（可在回收站恢复）",
    "toast_restored": "已恢复 {n} 项",
    "toast_purged": "已从回收站彻底删除",
    "toast_copied": "已复制：{what}",
    "toast_copied_path": "已复制路径",
    "toast_not_found": "文件不存在：{path}",
    "toast_clipboard_empty": "剪贴板为空，或内容无法识别",
    "toast_sent_clipboard": "内容已复制，到 {app} 中按 Ctrl+V 粘贴",
    "toast_sent_pasted": "已发送到 {app}",
    "toast_send_fail": "未找到可发送的前台窗口",
    "toast_data_moved": "数据目录已迁移到：{path}",
    "toast_data_move_fail": "迁移失败：{msg}",
    # 卡片右键
    "menu_open": "打开",
    "menu_copy": "复制",
    "menu_copy_path": "复制路径",
    "menu_send_foreground": "发送到前台窗口",
    "menu_show_in_explorer": "显示文件位置",
    "menu_change_type": "修改类型",
    "menu_pin": "置顶",
    "menu_unpin": "取消置顶",
    "menu_edit_notes": "编辑备注",
    "menu_view_text": "查看 / 编辑内容",
    "menu_delete": "删除",
    # 回收站
    "recycle_title": "回收站",
    "recycle_empty": "回收站是空的",
    "recycle_restore": "恢复",
    "recycle_purge": "彻底删除",
    "recycle_purge_all": "清空回收站",
    "recycle_keep_days": "条目保留 30 天，到期自动清理",
    "recycle_restored": "已恢复 {n} 项",
    "recycle_purged": "已彻底删除",
    # 通用按钮
    "ok": "确定",
    "cancel": "取消",
    "apply": "应用",
    "close": "关闭",
    "learn_more": "知道了",
    # 内容弹窗
    "text_content_title": "文本内容",
    "text_edit_save": "保存修改",
    "notes_title": "备注",
    "notes_placeholder": "给这条内容写点备注…",
    "notes_empty": "（无备注）",
    # 类型名
    "kind_file": "文件",
    "kind_image": "图片",
    "kind_link": "链接",
    "kind_text": "文本",
    "time_just_now": "刚刚",
    "time_min_ago": "{n} 分钟前",
    "time_hour_ago": "{n} 小时前",
    "time_yesterday": "昨天 {t}",
    # 新手上手
    "onboard_title": "三步上手中转站",
    "onboard_1": "① 在任意应用中按住内容（文件/文字/图片）拖动",
    "onboard_2": "② 拖动途中按 {hotkey}，面板会出现在鼠标旁",
    "onboard_3": "③ 在面板上松手即存入；拖出卡片即可取用",
    "onboard_more": "双击卡片用默认程序打开；右键可复制、发送到前台窗口。",
    "onboard_start": "开始使用",
    # 设置
    "settings_title": "设置",
    "settings_grp_summon": "呼出与窗口",
    "settings_hotkey": "全局快捷键",
    "settings_hotkey_bad": "快捷键无效：至少需要 Ctrl 或 Alt 组合，且不能只有修饰键",
    "settings_offset_x": "弹出偏移 X（px）",
    "settings_offset_y": "弹出偏移 Y（px）",
    "settings_auto_hide": "存入后自动收起",
    "settings_auto_hide_delay": "自动收起延时（毫秒）",
    "settings_pin_default": "呼出时默认钉住",
    "settings_remember_geom": "记忆窗口大小与钉住位置",
    "settings_panel_w": "面板宽度",
    "settings_panel_h": "面板高度",
    "settings_send_paste": "“发送到前台窗口”后自动按 Ctrl+V（模拟粘贴，默认关闭）",
    "settings_grp_record": "记录与隐私",
    "settings_ignore_list": "忽略清单（不记录来源/去向的应用，支持 * 通配）",
    "settings_ignore_add": "添加",
    "settings_ignore_del": "移除所选",
    "settings_ignore_hint": "例如 chrome.exe 或 WeChat*，回车添加",
    "settings_text_mirror": "文本条目镜像为独立 .txt 文件（数据目录 text/ 下）",
    "settings_grp_data": "数据",
    "settings_data_dir": "数据目录",
    "settings_data_dir_change": "更改…",
    "settings_data_dir_move_note": "更改后现有数据将整体移动到新位置，移动失败会自动回退。",
    "settings_backup_keep": "每日备份保留份数",
    "settings_backup_now": "立即备份",
    "settings_backup_done": "备份完成：{path}",
    "settings_backup_fail": "备份失败：{msg}",
    # 设置对话框
    "settings_hotkey_capture_hint": "点击后按下新的组合键（Ctrl/Alt + 字母等）",
    # 其他
    "unknown_app": "未知应用",
    "mime_unsupported": "无法识别拖入的内容格式",
    "dir": "文件夹",
    "report_disabled": "报表将在后续版本提供",
}
